/** Generated from references/capabilities.yaml. Do not edit this file. */
export type CapabilityKind = "package" | "mcp" | "extension" | "agent";

export type CapabilityDefinition = {
  readonly id: string;
  readonly kind: CapabilityKind;
  readonly purpose: string;
  readonly owner: string;
  readonly trigger: string;
  readonly prerequisites: readonly string[];
  readonly readiness: string;
  readonly fallback: string;
  readonly status_signal: {
    readonly source: string;
    readonly states: readonly string[];
    readonly description: string;
    readonly sensitive: false;
  };
  readonly probe: {
    readonly type: CapabilityKind;
    readonly name?: string;
    readonly server?: string;
    readonly launcher?: string | null;
    readonly required_env?: readonly string[];
    readonly auth?: string;
    readonly names?: readonly string[];
    readonly settings?: string;
    readonly guard?: string;
  };
  readonly package?: { readonly name: string; readonly spec: string };
  readonly mcp?: {
    readonly server: string;
    readonly launcher?: string | null;
    readonly required_env: readonly string[];
    readonly auth: string;
  };
  readonly extension?: { readonly name: string; readonly source: string };
  readonly agent?: {
    readonly names?: readonly string[];
    readonly settings?: string;
    readonly guard?: string;
    readonly source: string;
  };
  readonly install_state: { readonly action: string; readonly state: string };
  readonly source: Record<string, string>;
};

export const CAPABILITY_CONTRACT_VERSION = 1 as const;
// prettier-ignore
export const CAPABILITIES: readonly CapabilityDefinition[] = [
  {
    "id": "package.pi-mcp-adapter",
    "kind": "package",
    "purpose": "Load Pi MCP configuration and expose managed servers through the adapter proxy.",
    "owner": "Pi MCP adapter",
    "trigger": "Use when a task needs a configured managed MCP server; do not invoke it for unrelated local work.",
    "prerequisites": [
      "Pi CLI",
      "Pi MCP configuration"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Use native repository tools or report that managed MCP access is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not report authentication, server health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "pi-mcp-adapter"
    },
    "package": {
      "name": "pi-mcp-adapter",
      "spec": "npm:pi-mcp-adapter"
    },
    "install_state": {
      "action": "mcpAdapterAction",
      "state": "mcpAdapterState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-magic-context",
    "kind": "package",
    "purpose": "Provide long-session compaction continuity and cross-session project memory for Pi conversations.",
    "owner": "Pi Magic Context",
    "trigger": "Use when a long session needs compaction continuity or cross-session project memory; do not add a second memory layer.",
    "prerequisites": [
      "Pi CLI"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Continue with the active session and report that compaction continuity is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not persist or expose prompts, memory contents, or usage telemetry.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@cortexkit/pi-magic-context"
    },
    "package": {
      "name": "@cortexkit/pi-magic-context",
      "spec": "npm:@cortexkit/pi-magic-context"
    },
    "install_state": {
      "action": "piMagicContextAction",
      "state": "piMagicContextState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-usage",
    "kind": "package",
    "purpose": "Provide Pi usage reporting when the installed extension supports it.",
    "owner": "Pi usage extension",
    "trigger": "Use only when usage reporting is requested or the active Pi session exposes it; it is not a reason to add telemetry calls to unrelated work.",
    "prerequisites": [
      "Pi CLI"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Do not synthesize usage data; report that usage reporting is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; this contract does not persist usage telemetry or claim that the package was used in this session.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@sreetej510/pi-usage"
    },
    "package": {
      "name": "@sreetej510/pi-usage",
      "spec": "npm:@sreetej510/pi-usage"
    },
    "install_state": {
      "action": "piUsageAction",
      "state": "piUsageState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-anthropic-auth",
    "kind": "package",
    "purpose": "Provide Pi authentication support for Anthropic providers.",
    "owner": "Pi Anthropic auth extension",
    "trigger": "Use when Anthropic provider authentication is missing or explicitly needs attention; do not prompt for auth on unrelated tasks.",
    "prerequisites": [
      "Pi CLI",
      "User-approved provider authentication"
    ],
    "readiness": "The package is present in the local Pi package listing; provider authentication remains unverified.",
    "fallback": "Use an already configured provider or report that Anthropic authentication needs user action.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it never reads, prints, or persists credentials or tokens.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@gotgenes/pi-anthropic-auth"
    },
    "package": {
      "name": "@gotgenes/pi-anthropic-auth",
      "spec": "npm:@gotgenes/pi-anthropic-auth"
    },
    "install_state": {
      "action": "piAnthropicAuthAction",
      "state": "piAnthropicAuthState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-subagents",
    "kind": "package",
    "purpose": "Run b-agentic's custom planner, researcher, debugger, and reviewer agents from the main session.",
    "owner": "pi-subagents",
    "trigger": "Use when the main session delegates b-plan, b-research, b-debug, b-review, or b-agentic-audit to its named custom subagent.",
    "prerequisites": [
      "Pi CLI",
      "Managed b-agentic agent profiles"
    ],
    "readiness": "The package is present in the local Pi package listing; managed agent definitions are reported separately and provider readiness remains unverified.",
    "fallback": "Do not claim delegated workflow execution; report that pi-subagents needs installation or configuration.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not launch a child, inspect prompts, or claim provider authentication.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "pi-subagents"
    },
    "package": {
      "name": "pi-subagents",
      "spec": "npm:pi-subagents"
    },
    "install_state": {
      "action": "piSubagentsAction",
      "state": "piSubagentsState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "agent.b-agentic-subagent-profiles",
    "kind": "agent",
    "purpose": "Confirm that b-agentic's four managed custom subagent profiles are present locally.",
    "owner": "b-agentic installer",
    "trigger": "Check when a delegated workflow needs its managed b-agentic profile or when local delegation readiness is requested.",
    "prerequisites": [
      "Pi agent directory"
    ],
    "readiness": "All four managed profile files and their installed child-only read-only guard are present locally.",
    "fallback": "Do not claim custom delegation is ready; sync the managed b-agentic agent profiles and child-only guard.",
    "status_signal": {
      "source": "local-agent-profile-and-guard-files",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only the local existence of the managed profile files and child-only guard; it does not read prompts, launch a child, or claim provider authentication.",
      "sensitive": false
    },
    "probe": {
      "type": "agent",
      "names": [
        "b-planner",
        "b-researcher",
        "b-debugger",
        "b-reviewer"
      ],
      "guard": "subagent-read-only-guard.ts"
    },
    "agent": {
      "names": [
        "b-planner",
        "b-researcher",
        "b-debugger",
        "b-reviewer"
      ],
      "guard": "subagent-read-only-guard.ts",
      "source": "pi/agents"
    },
    "install_state": {
      "action": "subagentProfilesAction",
      "state": "subagentProfilesState"
    },
    "source": {
      "installer": "pi/scripts/install.sh",
      "profiles": "pi/agents",
      "guard": "pi/subagent-read-only-guard.ts"
    }
  },
  {
    "id": "agent.b-agentic-subagent-settings",
    "kind": "agent",
    "purpose": "Confirm that Pi has a local settings file for b-agentic's managed subagent defaults.",
    "owner": "b-agentic installer",
    "trigger": "Check when local delegation readiness is requested after b-agentic installs its subagent defaults.",
    "prerequisites": [
      "Pi settings file"
    ],
    "readiness": "The local Pi settings file exists; its values, provider availability, and authentication remain unverified.",
    "fallback": "Do not claim default subagent configuration is ready; merge the managed subagent settings through the installer.",
    "status_signal": {
      "source": "local-agent-settings-file",
      "states": [
        "configured",
        "missing",
        "unknown"
      ],
      "description": "Reports only local settings-file presence; it does not read settings values, credentials, provider configuration, or prompts.",
      "sensitive": false
    },
    "probe": {
      "type": "agent",
      "settings": "settings.json"
    },
    "agent": {
      "settings": "settings.json",
      "source": "pi/configs/subagents.user.template.json"
    },
    "install_state": {
      "action": "subagentSettingsAction",
      "state": "subagentSettingsState"
    },
    "source": {
      "installer": "pi/scripts/install.sh",
      "template": "pi/configs/subagents.user.template.json"
    }
  },
  {
    "id": "package.pi-ask-user-question",
    "kind": "package",
    "purpose": "Provide grouped structured choices for material user-facing decisions and blockers.",
    "owner": "Pi ask-user-question extension",
    "trigger": "Use for a material interactive decision or blocker that needs 2–4 concrete options; do not ask questions for routine confirmations.",
    "prerequisites": [
      "Pi CLI",
      "Interactive UI"
    ],
    "readiness": "The package is present in the local Pi package listing; an interactive UI is still required.",
    "fallback": "Ask one focused plain-text question when the package or interactive UI is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not persist question content or user responses.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@juicesharp/rpiv-ask-user-question"
    },
    "package": {
      "name": "@juicesharp/rpiv-ask-user-question",
      "spec": "npm:@juicesharp/rpiv-ask-user-question"
    },
    "install_state": {
      "action": "piAskUserQuestionAction",
      "state": "piAskUserQuestionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-todo",
    "kind": "package",
    "purpose": "Provide Pi's todo tool, /todos command, and persistent overlay.",
    "owner": "Pi Todo extension",
    "trigger": "Use when a Pi session needs its todo tool, /todos command, or persistent overlay; this package does not add a b-agentic todo workflow policy.",
    "prerequisites": [
      "Pi CLI"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Continue without Pi todo support or report that the todo tool is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not inspect todo content, overlay state, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@juicesharp/rpiv-todo"
    },
    "package": {
      "name": "@juicesharp/rpiv-todo",
      "spec": "npm:@juicesharp/rpiv-todo"
    },
    "install_state": {
      "action": "piTodoAction",
      "state": "piTodoState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "mcp.codegraph",
    "kind": "mcp",
    "purpose": "Answer repository-wide architecture, dependency/call-flow, impact, route, and affected-test questions.",
    "owner": "CodeGraph MCP",
    "trigger": "Select when repository-wide architecture, dependency/call-flow, route, impact, or affected-test analysis is central to the task and likely valuable; use an available index for that question and initialize an absent index only for that concrete qualifying question. Spanning files alone never justifies selection or initialization.",
    "prerequisites": [
      "CodeGraph CLI",
      "Lazy MCP entry configured",
      "Project index only when that concrete question requires it"
    ],
    "readiness": "The local configuration contains a CodeGraph entry and its launcher is available; index state and live server health are not probed.",
    "fallback": "Use native local search/read and report the resulting repository-wide coverage gap.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or claims an initialized index, external verification, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "codegraph",
      "launcher": "codegraph",
      "required_env": [],
      "auth": "none"
    },
    "mcp": {
      "server": "codegraph",
      "launcher": "codegraph",
      "required_env": [],
      "auth": "none"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.context7",
    "kind": "mcp",
    "purpose": "Provide versioned official framework, library, and API documentation facts.",
    "owner": "Context7 MCP",
    "trigger": "Use for a versioned external library/framework/API fact when local sources and lockfiles do not settle the question.",
    "prerequisites": [
      "Lazy MCP entry configured",
      "User-supplied Context7 API key"
    ],
    "readiness": "The local configuration contains a Context7 entry and a non-placeholder key is available; the service and authentication are not probed.",
    "fallback": "Use pinned local lockfiles or official bounded sources and state any unresolved version uncertainty.",
    "status_signal": {
      "source": "local-config-file-presence",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence; it never reads entry content or API-key values and never claims authentication, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "context7",
      "launcher": null,
      "required_env": [
        "CONTEXT7_API_KEY"
      ],
      "auth": "api-key"
    },
    "mcp": {
      "server": "context7",
      "launcher": null,
      "required_env": [
        "CONTEXT7_API_KEY"
      ],
      "auth": "api-key"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.brave-search",
    "kind": "mcp",
    "purpose": "Provide independent current web corroboration and specialized current search modalities.",
    "owner": "Brave Search MCP",
    "trigger": "Use when current or independent public-web corroboration is needed after local and primary-source research, or when a specialized search modality is requested.",
    "prerequisites": [
      "Bun bunx",
      "Lazy MCP entry configured",
      "User-supplied Brave Search API key"
    ],
    "readiness": "The local configuration contains a Brave Search entry, bunx is available, and a non-placeholder key is present; the service is not probed.",
    "fallback": "Use approved primary sources or state that independent current corroboration is unavailable.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or API-key values and never claims authentication, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "brave-search",
      "launcher": "bunx",
      "required_env": [
        "BRAVE_API_KEY"
      ],
      "auth": "api-key"
    },
    "mcp": {
      "server": "brave-search",
      "launcher": "bunx",
      "required_env": [
        "BRAVE_API_KEY"
      ],
      "auth": "api-key"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.firecrawl",
    "kind": "mcp",
    "purpose": "Provide bounded public extraction, developer research, papers, and GitHub lookup.",
    "owner": "Firecrawl MCP",
    "trigger": "Use for bounded primary public extraction or research when official docs and local evidence are insufficient; do not use it as a browser-evidence substitute.",
    "prerequisites": [
      "Bun bunx",
      "Lazy MCP entry configured",
      "User-supplied Firecrawl API key"
    ],
    "readiness": "The local configuration contains a Firecrawl entry, bunx is available, and a non-placeholder key is present; the service is not probed.",
    "fallback": "Use Context7, Brave, or other approved bounded sources and state the resulting coverage gap.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or API-key values and never claims authentication, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "firecrawl",
      "launcher": "bunx",
      "required_env": [
        "FIRECRAWL_API_KEY"
      ],
      "auth": "api-key"
    },
    "mcp": {
      "server": "firecrawl",
      "launcher": "bunx",
      "required_env": [
        "FIRECRAWL_API_KEY"
      ],
      "auth": "api-key"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.playwright",
    "kind": "mcp",
    "purpose": "Collect requested real-browser, live UI, visual, console/network, and e2e evidence.",
    "owner": "Playwright MCP",
    "trigger": "Use only when browser, live UI, screenshot, visual, or e2e evidence is requested or a stated verification gap requires it.",
    "prerequisites": [
      "Bun bunx",
      "Lazy isolated MCP entry configured",
      "Explicit approval for navigation, screenshots, and external or local artifacts as applicable"
    ],
    "readiness": "The local configuration contains an isolated Playwright entry and bunx is available; no browser is started and no live page is probed.",
    "fallback": "Use supplied or CI evidence and report that real-browser evidence remains unverified.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or claims a browser session, screenshot, external page state, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "playwright",
      "launcher": "bunx",
      "required_env": [],
      "auth": "none"
    },
    "mcp": {
      "server": "playwright",
      "launcher": "bunx",
      "required_env": [],
      "auth": "none"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.mobbin",
    "kind": "mcp",
    "purpose": "Provide real product UI screens, flows, and sections as bounded design-reference evidence.",
    "owner": "Mobbin MCP",
    "trigger": "Use only inside b-design reference gathering when local evidence leaves a real open direction or the user asked for references; never use it as a substitute for repo tokens and components.",
    "prerequisites": [
      "Lazy MCP entry configured",
      "Paid Mobbin plan",
      "Approval-gated in-session OAuth"
    ],
    "readiness": "The local configuration contains a Mobbin entry; the paid plan, OAuth state, and service are not probed.",
    "fallback": "Continue from local evidence, record that Mobbin references are unavailable, and never block or loop on authentication.",
    "status_signal": {
      "source": "local-config-file-presence",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence; it never reads entry content and never claims authentication, a paid plan, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "mobbin",
      "launcher": null,
      "required_env": [],
      "auth": "oauth"
    },
    "mcp": {
      "server": "mobbin",
      "launcher": null,
      "required_env": [],
      "auth": "oauth"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.shadcn",
    "kind": "mcp",
    "purpose": "Browse real shadcn registry items, examples, and add commands for frontend implementation.",
    "owner": "shadcn MCP",
    "trigger": "Use only inside b-frontend when the project already has a shadcn stack (components.json present); prefer registry components over bespoke equivalents.",
    "prerequisites": [
      "Bun bunx",
      "Lazy MCP entry configured",
      "Project components.json"
    ],
    "readiness": "The local configuration contains a shadcn entry and bunx is available; the registry service is not probed.",
    "fallback": "Implement from existing project components and tokens and state that registry lookup was unavailable.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or claims registry health or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "shadcn",
      "launcher": "bunx",
      "required_env": [],
      "auth": "none"
    },
    "mcp": {
      "server": "shadcn",
      "launcher": "bunx",
      "required_env": [],
      "auth": "none"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "extension.b-agentic-permissions",
    "kind": "extension",
    "purpose": "Apply first-party shell and filesystem permission policy to Pi tool calls.",
    "owner": "b-agentic permissions extension",
    "trigger": "Apply on every relevant Pi tool call; explicit deny and approval gates remain authoritative.",
    "prerequisites": [
      "Installed Pi extension entrypoint"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Do not claim b-agentic safety coverage when the entrypoint is absent; keep dangerous work gated by the remaining runtime controls.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not claim that a tool call occurred or that a decision was auto-approved.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-permissions.ts"
    },
    "extension": {
      "name": "b-agentic-permissions.ts",
      "source": "pi/extensions/b-agentic-permissions.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-mcp-permissions",
    "kind": "extension",
    "purpose": "Apply managed MCP and custom-tool approval policy.",
    "owner": "b-agentic MCP permissions extension",
    "trigger": "Apply when a managed MCP or custom tool operation is requested.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Canonical MCP operation policy"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Fail closed for unclassified or unsafe MCP/custom operations; do not bypass approval.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint and never claims that an MCP operation was executed.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-mcp-permissions.ts"
    },
    "extension": {
      "name": "b-agentic-mcp-permissions.ts",
      "source": "pi/extensions/b-agentic-mcp-permissions.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-auto-mode",
    "kind": "extension",
    "purpose": "Provide explicit opt-in automatic approval while retaining explicit denies.",
    "owner": "b-agentic auto-mode extension",
    "trigger": "Use only after the user explicitly enables /b-auto-mode and confirms the warning.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Interactive confirmation for enablement"
    ],
    "readiness": "The managed entrypoint exists; auto-mode itself remains off until explicitly enabled.",
    "fallback": "Use normal approval prompts and explicit deny behavior.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it never reports a persisted prompt, approval decision, or enabled state.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-auto-mode.ts"
    },
    "extension": {
      "name": "b-agentic-auto-mode.ts",
      "source": "pi/extensions/b-agentic-auto-mode.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-sync",
    "kind": "extension",
    "purpose": "Refresh managed b-agentic assets or installed runtime tooling from an active Pi session.",
    "owner": "b-agentic sync extension",
    "trigger": "Use only when the user explicitly invokes /b-sync or /b-update and accepts the applicable refresh boundary.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Interactive Pi session for refresh"
    ],
    "readiness": "The managed entrypoint exists; no refresh is started by a status snapshot.",
    "fallback": "Report that in-session refresh is unavailable and leave files unchanged.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it does not claim that an update ran or expose command output.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-sync.ts"
    },
    "extension": {
      "name": "b-agentic-sync.ts",
      "source": "pi/extensions/b-agentic-sync.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-status",
    "kind": "extension",
    "purpose": "Show a read-only local capability snapshot without starting managed services or persisting session content.",
    "owner": "b-agentic status extension",
    "trigger": "Use only when the user invokes /b-status or asks for local capability readiness.",
    "prerequisites": [
      "Installed Pi extension entrypoint"
    ],
    "readiness": "The managed entrypoint exists and can render the local snapshot.",
    "fallback": "Use the installer report and local files; do not infer live service or usage readiness.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; the snapshot itself remains in memory and never persists prompts, code, URLs, secrets, or usage telemetry.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-status.ts"
    },
    "extension": {
      "name": "b-agentic-status.ts",
      "source": "pi/extensions/b-agentic-status.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-preview-markdown",
    "kind": "extension",
    "purpose": "Render requested Markdown inline in the Pi TUI and provide source-copy commands.",
    "owner": "b-agentic Markdown preview extension",
    "trigger": "Use when an inline Markdown preview is requested or is the appropriate response presentation surface.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Pi TUI for inline rendering"
    ],
    "readiness": "The managed entrypoint exists; a TUI is required for inline rendering and no preview is opened by a status snapshot.",
    "fallback": "Return concise Markdown text or state that inline preview is unavailable outside the Pi TUI.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not persist preview content or claim that a preview was rendered.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-preview-markdown.ts"
    },
    "extension": {
      "name": "b-agentic-preview-markdown.ts",
      "source": "pi/packages/preview-markdown/extensions/b-agentic-preview-markdown.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  }
] as const;
export const CAPABILITY_IDS = new Set(
  CAPABILITIES.map((capability) => capability.id),
);
